=== yairm210/Unciv/docs/Modders/schemas/victoryTypes.json
{
    "$schema": "http://json-schema.org/draft-07/schema#",
    "title": "VictoryTypes",
    "type": "array",
    "items": {
        "type": "object",
        "properties": {
            "name": {
                "type": "string",
                "description": "Name of the victory"
            },
            "victoryScreenHeader": {
                "type": "string",
                "description": "Shown in the footer of the victory in the our status in the victory screen"
            },
            "victoryString": {
                "type": "string",
                "description": "Shown in the footer of the victory screen when you won the game with this victory"
            },
            "defeatString": {
                "type": "string",
                "description": "Shown in the footer of the victory screen when someone else won the game with this victory"
            },
            "hiddenInVictoryScreen": {
                "type": "boolean",
                "description": "Whether progress of this victory is hidden in the victory screen",
                "default": false
            },
            "requiredSpaceshipParts": {
                "type": "array",
                "items": { "type": "string" },
                "description": "Which units must be added to the capital for the corresponding milestone"
            },
            "milestones": {
                "type": "array",
                "items": { "type": "string" },
                "description": "List of milestones that must be accomplished to win. See https://yairm210.github.io/Unciv/Modders/Mod-file-structure/5-Miscellaneous-JSON-files/#milestones"
            },
            "civilopediaText": { "$ref": "https://raw.githubusercontent.com/yairm210/Unciv/master/docs/Modders/schemas/civilopediaText.json" }
        },
        "required": ["name", "milestones"],
        "additionalProperties": false
    }
}

=== yairm210/Unciv/android/assets/jsons/Civ V - Vanilla/VictoryTypes.json
[
    {
        "name": "Scientific",
        "victoryScreenHeader": "Complete all the spaceship parts\nto win!",
        "milestones": [
            "Build [Apollo Program]", "Add all [spaceship parts] in capital"
        ],
        "requiredSpaceshipParts": [
            "SS Engine", "SS Stasis Chamber", "SS Cockpit", "SS Booster", "SS Booster", "SS Booster"
        ],
        "victoryString": "You have achieved victory through mastery of Science! You have conquered the mysteries of nature and led your people on a voyage to a brave new world! Your triumph will be remembered as long as the stars burn in the night sky!",
        "defeatString": "You have been defeated. Your civilization has been overwhelmed by its many foes. But your people do not despair, for they know that one day you shall return - and lead them forward to victory!"
    },
    {
        "name": "Cultural",
        "victoryScreenHeader": "Complete 5 policy branches and\nbuild the Utopia Project to win!",
        "milestones": ["Complete [5] Policy branches", "Build [Utopia Project]"],
        "victoryString": "You have achieved victory through the awesome power of your Culture. Your civilization's greatness - the magnificence of its monuments and the power of its artists - have astounded the world! Poets will honor you as long as beauty brings gladness to a weary heart.",
        "defeatString": "You have been defeated. Your civilization has been overwhelmed by its many foes. But your people do not despair, for they know that one day you shall return - and lead them forward to victory!"
    },
    {
        "name": "Domination",
        "victoryScreenHeader": "Capture all enemy Capitals\nto win!",
        "milestones": ["Capture all capitals"],
        "victoryString": "The world has been convulsed by war. Many great and powerful civilizations have fallen, but you have survived - and emerged victorious! The world will long remember your glorious triumph!",
        "defeatString": "You have been defeated. Your civilization has been overwhelmed by its many foes. But your people do not despair, for they know that one day you shall return - and lead them forward to victory!"
    },
    {
        "name": "Diplomatic",
        "victoryScreenHeader": "Build the UN and be voted\nworld leader to win!",
        "milestones": ["Anyone should build [United Nations]", "Win diplomatic vote"],
        "victoryString": "You have triumphed over your foes through the art of diplomacy! Your cunning and wisdom have earned you great friends - and divided and sown confusion among your enemies! Forever will you be remembered as the leader who brought peace to this weary world!",
        "defeatString": "You have been defeated. Your civilization has been overwhelmed by its many foes. But your people do not despair, for they know that one day you shall return - and lead them forward to victory!"
    },
    {
        "name": "Time",
        "hiddenInVictoryScreen": true,
        "milestones": ["Have highest score after max turns"],
        "victoryString": "The world has been convulsed by war. Many great and powerful civilizations have fallen, but you have survived - and emerged victorious! The world will long remember your glorious triumph!",
        "defeatString": "You have been defeated. Your civilization has been overwhelmed by its many foes. But your people do not despair, for they know that one day you shall return - and lead them forward to victory!"
    }
]
